feat: implement events
Dead-Bread-Inside/Eventures pull request #13
Opened 2022-08-11 10:04 UTC by Makentoshe

- implement Category for events

- implement Distance class and EventsRepository

- implement Event, Location and User entities

Closes #7

2022-08-18 21:27 UTC, Indorian1996 commented on app/src/main/java/eu/deadbread/eventures/entities/Category.kt
> +sealed class Category {
I suggest to use Category as Data class with name: String and children: List<Category>. Also we can manage color from FB by "colorHex" field. And we can create CategoryType as enum class for cases when we would like change something on our side

2022-08-18 21:38 UTC, Indorian1996 commented on app/src/main/java/eu/deadbread/eventures/viewmodel/MapScreenViewModel.kt
> +            eventsInArea = eventsRepository.getEventsInArea(deviceLocation, Distance.Meters(5000))
Suggest to add consts file into "common" module and add METERS_IN_KILOMETERS = 1000 and use `5*METERS_IN_KILOMETERS`

2022-08-18 21:38 UTC, Indorian1996 requested changes
check comments

2022-08-19 09:12 UTC, Makentoshe commented on app/src/main/java/eu/deadbread/eventures/entities/Category.kt
> +sealed class Category {
I decide to postpone CategoryType until we will be sure we need it

2022-08-22 08:31 UTC, Indorian1996 commented on app/src/main/java/eu/deadbread/eventures/entities/Category.kt
> +data class Category(val title: String, val color: Color, val childs: List<Category> = emptyList())
children
colorHex: String

2022-08-22 08:43 UTC, Makentoshe commented on app/src/main/java/eu/deadbread/eventures/entities/Category.kt
> +data class Category(val title: String, val color: Color, val childs: List<Category> = emptyList())
Done

2022-08-22 09:49 UTC, Indorian1996 approved these changes

2022-08-22 09:49 UTC, merged